version: '3'
services:
  mysqldatabase:
    image: mysql:5.7
    container_name: mysqldatabase
    environment:
      MYSQL_ROOT_PASSWORD: pruebanodejs
      MYSQL_DATABASE: pruebanodejs
      MYSQL_USER: pruebanodejs
      MYSQL_PASSWORD: pruebanodejs
      MYSQL_HOST: "0.0.0.0"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - appnetwork
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: app_prueba_nodejs
    image: prueba-nodejs
    ports:
      - "3000:3000"
    networks:
      - appnetwork
    links:
      - mysqldatabase:mysqldatabase
    depends_on:
      - mysqldatabase
    environment:
      - WAIT_HOSTS=0.0.0.0:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    # restart: on-failure
networks:
  appnetwork:
    driver: bridge
